### ISSUE TITLE
Add new date format for field "Interval"

### ISSUE THREAD

**Issue by stratewarius** [albertodonato/query-exporter#29]
Hi Alberto!
Improve field "Interval":
add possibility use date format like a crontab: 
[Minute] [hour] [Day_of_the_Month] [Month_of_the_Year] [Day_of_the_Week]

**Comment by IldarMinaev** [comment]
Hi @albertodonato , @stratewarius 
I tried to add this type of future with new field croniter:
(https://github.com/IldarMinaev/query-exporter/commit/ddd2a8cfa3c8d6d995339eaa9cf6975e385e14d4)

**Comment by albertodonato** [comment]
@IldarMinaev thanks for having a stab at the issue.

Unfortunately I don't think adding the croniter field is enough, as it can't really reuse the `interval`. There's no guarantee that the interval at which a cron-like rule is executed is constant.

I'm thinking a possible way to implement it would be to have a variant of `PeriodicCall` which takes an iterator like the one returned by `croniter()` to schedule call executions.
I'll see if I can add something like that.

I'm also not sure about using cron syntax, I'm not a big fan of that since it's not very readable.
One option would probably be to use rrule format. I'll take a look at that too.

**Comment by albertodonato** [comment]
I added a `schedule` field (alternative to `interval`) which uses the cron format via croniter.
Thanks @IldarMinaev for the suggestion.

Let me know if it works as expected.
