### ISSUE TITLE
Question: dynamic reload of configuration file

### ISSUE THREAD

**Issue by kduvekot** [albertodonato/query-exporter#41]
Not a bug or feature request (yet) .. but is the configuration file automatically reload when its changed? 
That way we could manage the configuration file outside of the docker container for the exporter and use a Volume to link the configuration file into the docker.
And by using env variables we can also remove any user/password from the configuration file so new Databases/Metrics/Queries can be added without changing the running instance (and possibly impacting metrics)

**Comment by albertodonato** [comment]
Hi, no, the configuration file is read at startup. If you change it, you should just restart the exporter.

Implementing dynamic reload would be quite hard, since it'd have to track all kind of changes (added/removed/changed dbs, metrics, queries,...). It would really end up being equivalent to restarting the service.

There are tools that track changes to files and can perform actions when that happens. Maybe you could use something like this to restart the exporter when the file is changed?

**Comment by xuanyuanaosheng** [comment]
@albertodonato   if you use Kubernetes, maybe stakater-reloader can help you.
