### ISSUE TITLE
Protect the metrics endpoint with auth

### ISSUE THREAD

**Issue by muteid10t** [albertodonato/query-exporter#83]
Could you add support for protecting the metrics endpoint with authentication.
Prometheus supports it as part of the scrape config and from a security standpoint it's basically become an industry best practice to protect endpoints like these with authentication.

**Comment by albertodonato** [comment]
That sounds like a useful feature, shouldn't be too hard to add

**Comment by albertodonato** [comment]
While looking around to see what other exporters do, I ran into https://github.com/prometheus/node_exporter/issues/100.
Basically to provide any security value authentication should also happen over HTTPS.
Usually that's done not directly in the server, but via a reverse proxy (like nginx or apache) which can provide both HTTPS and basic auth.

I think that would be a better way to go, rather than duplicating efforts in each exporter.

**Comment by albertodonato** [comment]
Given the discussion on the similar issue linked above, I'll close this issue.
